routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->middleware('auth');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');
Route::resource('tutoriels', 'TutorielController');
Route::resource('questionnaires', 'QuestionnaireController');
Route::resource('topic', 'TopicController');
Route::resource('offres', 'OffreController');

app/Http/Controllers/OffreController.php
<?php

namespace ASI_lytics\Http\Controllers;

use Illuminate\Http\Request;

class OffreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $offres = Offre::all();
        return view('offres.index', compact('offres'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('offres.createOffres');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titreOffre'=>'required',
            'niveauEtude'=>'required',
            'pdf'=>'required',
            'descriptionOffre'=>'required'
        ]);
        $contact = new Offre([
            'titreOffre' => $request->get('titreOffre'),
            'niveauEtude' => $request->get('niveauEtude'),
            'pdf' => $request->get('pdf'),
            'descriptionOffre' => $request->get('descriptionOffre')
        ]);
        $contact->save();
        return redirect('/offres')->with('success', 'Offre saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($idOffre)
    {
        $offre = Offre::find($idOffre);
        return view('offres.editOffres', compact('offres'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $idOffre)
    {
        $request->validate([
            'titreOffre'=>'required',
            'niveauEtude'=>'required',
            'pdf'=>'required',
            'descriptionOffre'=>'required'
        ]);
        $offre = Offre::find($idOffre);
        $offre->titreOffre =  $request->get('titreOffre');
        $offre->niveauEtude = $request->get('niveauEtude');
        $offre->pdf = $request->get('pdf');
        $offre->descriptionOffre = $request->get('descriptionOffre');
        $offre->save();
        return redirect('/offres')->with('success', 'Offre updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($idOffre)
    {
        $offre = Offre::find($idOffre);
        $offre->delete();
        return redirect('/offres')->with('success', 'Offre deleted!');
    }
}

resources/views/offres/create.blade.php
@extends('base')
@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Crée une offre</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('offres.store') }}">
          @csrf
          <div class="form-group">    
              <label for="titreOffre">Titre:</label>
              <input type="text" class="form-control" name="titreOffre"/>
          </div>
          <div class="form-group">
              <label for="niveauEtude">Niveau d'étude:</label>
              <input type="text" class="form-control" name="niveauEtude"/>
          </div>
          <div class="form-group">
              <label for="pdf">PDF:</label>
              <input type="text" class="form-control" name="pdf"/>
          </div>
          <div class="form-group">
              <label for="descriptionOffre">Description:</label>
              <input type="text" class="form-control" name="descriptionOffre"/>
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Ajouter</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/offres/createOffres.blade.php
@extends('template/adminTemplate')
@section('content')
<!-- Main content -->
<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            {!! Form::open(['route' => "offres.store", 'method' => 'post', 'files' => true]) !!}
            <div class="box-header">
                <h3 class="box-title">  </h3>

                <div class="form-group">
                    <label>Titre:  </label>
                    <input class="form-control" placeholder="titre" name="titre">
                </div>
            </div>

            <div class="form-group" style="width:200px;">
                <label for="role" class="control-label">Niveau d'étude</label>
                   <select class="form-control" id="niveauEtude" name="niveauEtude">
                   <option value="1">Bac+2</option>
                   <option value="2">Bac+3</option>
                   <option value="3">Bac+4</option>
                   <option value="4">Bac+5</option>
                   <option value="5">Autres</option>
                </select>
               </div>

                <div class="form-group">
                    <label>Ajout d'un PDF:  </label>
                    <input class="form-control" placeholder="PDF" name="PDF">
                </div>
            </div>

            <div class="box-header">
                <h3 class="box-title">  </h3>
                <div class="form-group">
                    <label>Description:  </label>
                    <input class="form-control" placeholder="description" name="description">
                </div>
            </div>


            <!-- /.box-header -->
            <div class="box-body pad">

                <div class="form-group">
                    {{ Form::textarea('editor', '',['id'=>'editor','class'=>'form-control','placeholder'=>'Rentrer la description des animaux ici']) }}
                </div>

            </div>

            <div class="form-group">
                <a href="" class="popup_selector" data-inputid="feature_image"><label for="feature_image">Selectionner Image</label></a>                   
                <input type="text" id="feature_image" name="image" value="">
            </div>

            <button type="submit" class="btn btn-success btn-lg btn-block">Créer</button>

            {!! Form::close() !!}
        </div>
        <!-- /.box -->
    </div>
</div>

<!--script elfinder -->
<script type="text/javascript" src="/packages/barryvdh/elfinder/js/standalonepopup.min.js"></script>
@stop

resources/views/offres/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Modifier une offre</h1>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('offres.update', $offre->idOffre) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">
                <label for="titreOffre">Titre:</label>
                <input type="text" class="form-control" name="titreOffre" value={{ $offre->titreOffre }} />
            </div>
            <div class="form-group">
                <label for="niveauEtude">Niveau d'étude:</label>
                <input type="text" class="form-control" name="niveauEtude" value={{ $offre->niveauEtude }} />
            </div>
            <div class="form-group">
                <label for="pdf">PDF:</label>
                <input type="text" class="form-control" name="pdf" value={{ $offre->pdf }} />
            </div>
            <div class="form-group">
                <label for="descriptionOffre">Description:</label>
                <input type="text" class="form-control" name="descriptionOffre" value={{ $offre->descriptionOffre }} />
            </div>
            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
    </div>
</div>
@endsection

resources/views/offres/editOffres.blade.php
@extends('template/adminTemplate')
@section('content')
<!-- Main content -->
<div class="row">
    <div class="col-md-12">
        <div class="box box-info">
            {!! Form::open(['route' => ["offres.edit", $offre["idOffre"]], 'method' => 'put']) !!}
            <div class="box-header">
                <h3 class="box-title">  </h3>

                <div class="form-group">
                    <label>Titre:  </label>
                    <input class="form-control" name="nom" value={{$offre["titreOffre"]}}>
                </div>
            </div>

            <div class="box-header">
                <h3 class="box-title">  </h3>

                <div class="form-group" style="width:200px;">
                    <label for="role" class="control-label">Niveau d'étude</label>
                       <select class="form-control" id="niveauEtude" name="niveauEtude">
                       <option value="1">Bac+2</option>
                       <option value="2">Bac+3</option>
                       <option value="3">Bac+4</option>
                       <option value="4">Bac+5</option>
                       <option value="5">Autres</option>
                    </select>
                   </div>

                <div class="form-group">
                    <label> modifier le PDF:  </label>
                    <input class="form-control" name="prenom" value={{$offre["pdf"]}}>
                </div>
            </div>

            <div class="box-header">
                <h3 class="box-title">  </h3>

                <div class="form-group">
                    <label>Description:  </label>
                    <input class="form-control" name="description" value={{$offre["descriptionOffre"]}}>
                </div>
            </div>

            <!-- /.box-header -->
            <div class="box-body pad">

                <div class="form-group">
                    {{ Form::textarea('editor', $offre["descriptionOffre"],['id'=>'editor','class'=>'form-control']) }}
                </div>

            </div>

            <button type="submit" class="btn btn-success btn-lg btn-block">Modifier</button>

            {!! Form::close() !!}
        </div>
        <!-- /.box -->
    </div>
</div>
@stop

resources/views/offres/index.blade.php
@extends('base')
@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Offres</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Titre</td>
          <td>Etude</td>
          <td>PDF</td>
          <td>Description</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($offres as $offre)
        <tr>
            <td>{{$offre->idOffre}}</td>
            <td>{{$offre->titreOffre}}</td>
            <td>{{$offre->niveauEtude}}</td>
            <td>{{$offre->pdf}}</td>
            <td>{{$offre->descriptionOffre}}</td>
            <td>
                <a href="{{ route('offres.edit',$offre->idOffre)}}" class="btn btn-primary">Modifier</a>
            </td>
            <td>
                <form action="{{ route('offres.destroy', $offre->idOffre)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Supprimer</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
</div>
@endsection

resources/views/offres/modifyOffres.blade.php
@extends('template/adminTemplate')

@section('content')
<table class="table table-bordered">
    <thead class="thead-inverse">
        <tr>
            <th style="width: 2px">#</th>
            <th style="width: 10px">Titre</th>
            <th>Niveau d'Etude</th>
            <th>PDF</th>
            <th>Description</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($LesOffres as $uneOffre)
        <tr>
            <td class="col-md-1">
                {{ $uneOffre["idOffre"] }}
            </td>

            <td class="col-md-1">
                {{ $uneOffre["titreOffre"] }}
            </td>
            <td class="col-md-2">
                {{ $uneOffre["niveauEtude"] }}
            </td>
            <td class="col-md-4">
                {{ $uneOffre["pdf"] }}
            </td>
            <td class="col-md-4">
                {{ $uneOffre["descriptionOffre"] }}
            </td>

            <td class="col-md-1">
            {{ Form::open(['route'=>['offres.destroy',$uneOffre->idOffre], 'method' => 'delete']) }}
            {{Form::submit('Supprimez',["class"=>"btn btn-block btn-danger"])}}
            {{ Form::close() }}
            </td>
            <td class ="col-md-1">
            {{ Form::open(['route'=>['offres.edit',$uneOffre->idOffre],"method"=>"get"]) }}
            {{Form::submit('Editer',["class"=>"btn btn-warning btn-block"])}}
            {{ Form::close() }}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@stop

resources/views/offres/offres.blade.php
@extends('template/template')
@section('title')
Menu principal
@stop

@section('content')
@stop